package interview;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapFlatMapExample {

	public static void main(String[] args) {
		flatmapmethod();
		flatmapMethodTwo();
		
		mapMethod();
		mapMethodExampleTwo();
	}

	private static void flatmapmethod() {
		// TODO Auto-generated method stub
		List<String> lines = List.of("Java 8", "Stream API");

		// remember below syntax
		List<String> words = lines.stream()
		    .flatMap(line -> Arrays.stream(line.split(" ")))
		    .collect(Collectors.toList());

		System.out.println(words); // [Java, 8, Stream, API]
	}
	
	private static void mapMethod() {
		// TODO Auto-generated method stub
		List<String> words = List.of("Java", "Stream");

		List<Integer> lengths = words.stream()
		    .map(String::length)
		    .collect(Collectors.toList());

		System.out.println(lengths); // [4, 6]

	}
	
	private static void  flatmapMethodTwo(){
		 // making the arraylist object of List of Integer
        List<List<Integer> > number = new ArrayList<>();
      
        // adding the elements to number arraylist
        number.add(Arrays.asList(1, 2));
        number.add(Arrays.asList(3, 4));
        number.add(Arrays.asList(5, 6));
        number.add(Arrays.asList(7, 8));
      
        System.out.println("List of list-" + number);
      
        // using flatmap() to flatten this list
        List<Integer> flatList
            = number.stream()
                  .flatMap(list -> list.stream())
                  .collect(Collectors.toList());
      
        // printing the list
        System.out.println("List generate by flatMap-"
                           + flatList);
    }
	
	private static void  mapMethodExampleTwo(){
		 // making the array list object
        ArrayList<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");
        System.out.println("List of fruit-" + fruit);
      
        // lets use map() to convert list of fruit
        List list = fruit.stream()
                        .map(s -> s.length())
                        .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);
	}
}
